version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: python /app/recipes/manage.py runserver 0.0.0.0:8000
